---
- ros_topic_name: "command/motor_speed"
  gz_topic_name: "/x500/command/motor_speed"
  ros_type_name: "actuator_msgs/msg/Actuators"
  gz_type_name: "gz.msgs.Actuators"
  direction: ROS_TO_GZ
- gz_topic_name: "/world/default/model/x500/joint_state"
  ros_topic_name: "joint_states"
  gz_type_name: "gz.msgs.Model"
  ros_type_name: "sensor_msgs/msg/JointState"
  direction: GZ_TO_ROS
- gz_topic_name: "/world/default/model/x500/link/chassis_link/sensor/imu_sensor/imu"
  ros_topic_name: "imu"
  gz_type_name: "gz.msgs.IMU"
  ros_type_name: "sensor_msgs/msg/Imu"
  direction: GZ_TO_ROS
- gz_topic_name: "/world/default/model/x500/link/chassis_link/sensor/navsat_sensor/navsat"
  ros_topic_name: "gps/fix"
  gz_type_name: "gz.msgs.NavSat"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  direction: GZ_TO_ROS
- gz_topic_name: "/world/default/model/x500/link/chassis_link/sensor/air_pressure_sensor/air_pressure"
  ros_topic_name: "air_pressure"
  gz_type_name: "gz.msgs.FluidPressure"
  ros_type_name: "sensor_msgs/msg/FluidPressure"
  direction: GZ_TO_ROS
- gz_topic_name: "/world/default/clock"
  ros_topic_name: "clock"
  gz_type_name: "gz.msgs.Clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  direction: GZ_TO_ROS